### ISSUE TITLE
Xml2Js is missing

### ISSUE THREAD

**Issue by asl** [jgraph/drawio#198]
ant build depends on Xml2Js, however it seems to be missing in the repo and there are no docs indicating where to obtain it. So far we're having:

```
merge:
     [java] Could not find Xml2Js. Make sure you have it in your classpath
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:139)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:772)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:222)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:136)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:109)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:497)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
     [java] Java Result: -1
```

**Comment by alderg** [comment]
Which build file, please?

**Comment by asl** [comment]
etc/build/build.xml

You could see the same error message on Travis builds: https://travis-ci.org/jgraph/drawio

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
