### ISSUE TITLE
Variable GitLabClient.prototype.redirectUri gets wrong redirection Uri (.html ommited) thus Gitlab repo authorization fails on self-hosted instances

### ISSUE THREAD

**Issue by tafkos** [jgraph/drawio#2192]
Recent releases of diagrams.net (not sure but at least in 14.9.7)  self-hosted docker instance cannot authorize in GitLab 14.1.2 self-hosted instance as well). I thought this fails was due to some misconfiguration from my side... but..

https://github.com/jgraph/drawio/blob/609d031c9430ae737dc30fb11ac11709fb63a19d/src/main/webapp/js/diagramly/GitLabClient.js#L44

It is strange that `.html` has been missed ^^^ while it is explicitly emphasized in Guides ([link1](https://itectec.com/webapp/how-to-integrate-diagrams-net-draw-io-with-self-hosted-gitlab/),  jgraph/drawio#493 ), that `gitlab.html` is important!

Suggested fix:
```diff
---GitLabClient.prototype.redirectUri = window.location.protocol + '//' + window.location.host + '/gitlab'; 
+++GitLabClient.prototype.redirectUri = window.location.protocol + '//' + window.location.host + '/gitlab.html'; 
```
[this workaround](493#issuecomment-685683251) worked before GitLab authetication process upgraded since release 14.6.7 and [docker-drawio] corresponding upgrade](https://github.com/jgraph/docker-drawio/commit/d52488974a0f7740a17c66929ba4943ecc4ccb1a). Nowdays similar way doesn't work...

**Comment by tafkos** [comment]
seems I found one more occurence of the bug:  
https://github.com/jgraph/drawio/blob/9425639430927146ef0c52a5dc34f20f0044008b/src/main/java/com/mxgraph/online/GitlabAuthServlet.java#L60

Shouldn't it be like this:

```diff
--- CONFIG.REDIRECT_PATH = "/gitlab"; 
+++ CONFIG.REDIRECT_PATH = "/gitlab.html"; 
```

**Comment by lfvjimisola** [comment]
Think we stumbled on this issue as well. Do you happen to have a previous version number where the integration works?

**Comment by tafkos** [comment]
> 
> 
> Think we stumbled on this issue as well. Do you happen to have a previous version number where the integration works?

I have investigated history of releases and noticed 
```
28-APR-2021: 14.6.7

- Switches to server flow for GitHub and Gitlab auth
``` 

So buggy LOCs had been appeared right after this release. `.html` is omitted in variable `GitLabClient.prototype.redirectUri`:
https://github.com/jgraph/drawio/blob/9425639430927146ef0c52a5dc34f20f0044008b/src/main/webapp/js/diagramly/GitLabClient.js#L44

Previously it was correctly assigned with `.html`:
https://github.com/jgraph/drawio/blob/126fd25c300fb63b0a917c589f7175b20e9e4955/src/main/webapp/js/diagramly/GitLabClient.js#L55

Later I try to deploy release 14.6.6 as recent release before  Gitlab auth changed

**Comment by tafkos** [comment]
releases older than 14.6.7 requires also downgrade gitlab... so I can't deploy old drawio...

**Comment by davidjgraph** [comment]
/gitlab is the correct path, not gitlab.html

How are you running the server part of this project, do you have the gitlab servlet running and responding correctly?

**Comment by lfvjimisola** [comment]
> /gitlab is the correct path, not gitlab.html
> 
> How are you running the server part of this project, do you have the gitlab servlet running and responding correctly?

We're getting a "The redirect URI included is not valid." when we use "/gitlab" as in "somehost.com/gitlab".

Any idea what causes this? What GitLab servlet is it that needs to be running?

Loading "somehost.com/gitlab" in a browser results in a 404.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/blob/dev/src/main/java/com/mxgraph/online/GitlabAuthServlet.java

How are you serving the project? I'm looking for technical specifics.

**Comment by lfvjimisola** [comment]
We have used the fix as in #2193. 

As for servlet and serving the project we aren't following.
What do you mean by serving the project? Do we need to activate or configure something else?

We are running a self-hosted GitLab and DrawIO runs as a container inside an OpenShift cluster.
We are setting thethe following environment variables:

* DRAWIO_GITLAB_ID
* DRAWIO_GITLAB_URL
* DRAWIO_BASE_URL

but not

* DRAWIO_GITLAB_SECRET

**Comment by davidjgraph** [comment]
This is a drawio docker image? If so, which one? does YOURDOMAIN/gitlab respond?

**Comment by tafkos** [comment]
https://Drawio.My.domain.com/gitlab.html : "This window will be closed automatically."

https://Drawio.My.domain.com/gitlab: HTTP ERROR 400

Moreover, I have added .html to redirectUri, rebuilt docker image of drawio, and now almost everything is passed ok, except finally drawio notify that access is denied... So this simple workaround is not the solution, need to debug auth process

**Comment by davidjgraph** [comment]
We don't support the deprecated implicit flow grant, nor does Gitlab any further.

This is a drawio docker image? If so, which one?

Basically, I'm asking you what you are running, you need to answer my questions for us to help.

**Comment by tafkos** [comment]
My configuration is as follows:
1) Host: ubuntu 20.04 LTS
2) Gitlab 14.2.1 running from recent deb package
3) drawio - most recent docker image 15.0.6, but also tried 14.6.7, and rebuilt from source after adding .html 4.6.7

**Comment by davidjgraph** [comment]
OK, but https://github.com/jgraph/docker-drawio and not https://github.com/fjudith/docker-draw.io ?

**Comment by tafkos** [comment]
https://github.com/jgraph/docker-drawio

**Comment by tafkos** [comment]
'''yaml
  drawio:                                                                 
    image: jgraph/drawio                                                  
#    image: jgraph/drawio:14.2.6                                          
#    image: drawio:custom                                                 
#    image: drawio:custom_v14.9.7
'''
Tried all of them...

**Comment by davidjgraph** [comment]
OK, thanks for the info. Does the docker image have any writable disk assigned? The auth process is a stateful process, so the initial handshake with the client needs to record a token to check it's the same client when the redirect URL is invoked.

**Comment by ellakk** [comment]
> This is a drawio docker image? If so, which one? does YOURDOMAIN/gitlab respond?

I'm with lfvjimisola. We are using the docker image: jgraph/drawio:15.0.6 with the GitLabClient.js  from https://github.com/jgraph/drawio/pull/2193. When we try to authorize we get the following error: **An error has occurred. The redirect URI included is not valid.**

We have tried setting the redirect url to both https://ourcopanygitlab.com/gitlab.html and https://ourcopanygitlab.com/gitlab

**Comment by davidjgraph** [comment]
In your Gitlab project for the drawio app have you set the redirect URL correctly?

**Comment by ellakk** [comment]
> In your Gitlab project for the drawio app have you set the redirect URL correctly?

We belive so:
![drawio](https://user-images.githubusercontent.com/23560879/132208338-3188384b-b465-438b-8fd7-7315197a5fb0.jpg)

**Comment by tafkos** [comment]
I tried both

**Comment by tafkos** [comment]
I tried both options, neither works:
1) https://Drawio.My.domain.com/gitlab.html
2) https://Drawio.My.domain.com/gitlab

**Comment by davidjgraph** [comment]
Sorry, I can't track two cases at the same time in one thread. @ellakk please start a new thread with all the details from this one.

**Comment by davidjgraph** [comment]
@tafkos you don't get this redirect issue, I assume?

**Comment by tafkos** [comment]
@davidjgraph
 is there any recent documentation about how to configure gitlab+drawio selfhost integration?
I know just this one: https://itectec.com/webapp/how-to-integrate-diagrams-net-draw-io-with-self-hosted-gitlab/

----
> you don't get this redirect issue, I assume?



> I tried both options, neither works:
> 
>     1. https://Drawio.My.domain.com/gitlab.html
> 
>     2. https://Drawio.My.domain.com/gitlab

I do have this redirection issue as actually I started this thread hahaha 😆 , but redirection seems to me started working after I rebuilt  docker image using jgraph/drawio:v14.9.7 tag with proposed [change ](https://github.com/jgraph/drawio/issues/2192#issuecomment-901962845) applied. However, authentication still stuck and drawio shoes "Access denied" window. Let me later provide snapshots of the process on modified image...

**Comment by davidjgraph** [comment]
No, but we'll write some once we work out what the problem everyone is having. That link is out of date.

It will work with gitlab.html, but Gitlab are killing implicit grant and that's what that URL is for. We were named as top offended for using it, https://gitlab.com/gitlab-org/gitlab/-/issues/288516#note_500804868, so we need to stop.

Please switch back to /gitlab, that's the one we need to get working.

**Comment by tafkos** [comment]
> https://gitlab.com/gitlab-org/gitlab/-/issues/288516#note_500804868
Aha!!! I was so frustrated by the fact that same config with newest Gitlab 14+ release works at another site which works very long time, but a new one config I created recently doesn't work (where new application for drawio was created)!
So I try to switch to older gitlab and  try... however, it might take some time for me...

**Comment by tafkos** [comment]
> Please switch back to /gitlab, that's the one we need to get working.

In this case please notice that option 
> 2. https://Drawio.My.domain.com/gitlab

Shows HTML ERROR 400 when trying to access directly to this link

**Comment by tafkos** [comment]
Should we rename the issue ?
```diff
--- Variable GitLabClient.prototype.redirectUri gets wrong redirection Uri (.html ommited) thus Gitlab repo authorization fails on self-hosted instances
+++ Gitlab repo authorization fails on self-hosted instances of Gitalb v14.x.x and Drawio 
```

**Comment by davidjgraph** [comment]
Staying with /gitlab, you do have all of these set:

    DRAWIO_GITLAB_ID
    DRAWIO_GITLAB_URL
    DRAWIO_BASE_URL
    DRAWIO_GITLAB_SECRET

**Comment by tafkos** [comment]
```shell
$ cat docker-compose.yml |grep 'URL\|GITLAB'
```

```yaml                                                       
      - DRAWIO_BASE_URL=https://drawio.xxxxx.ru                        
      - DRAWIO_SERVER_URL=${DRAWIO_BASE_URL}                              
      - PLANTUML_URL=http://plantuml-server:8080/                         
      - EXPORT_URL=http://image-export:8000/                              
      - DRAWIO_BASE_URL=https://drawio.xxxxx.ru                        
      - DRAWIO_VIEWER_URL="https://drawio.xxxxx.ru"                    
      - DRAWIO_GITLAB_ID=xxxxb2aaa61eb2ee2ca3982fc6aa9492e9cf19f107c828f4759f56d649241266                                                           
      - DRAWIO_GITLAB_SECRET=xxxx9ad92cb97eedde128d5bf002034c07989ecfa4ee46b6ef03f7961a63594c                                                       
      - DRAWIO_GITLAB_URL=https://gitlab.xxxxx.ru
```

**Comment by davidjgraph** [comment]
Looks good. In the Gitlab application settings the callback URL is:

   https://drawio.xxxxx.ru/gitlab

And the scopes are:

    api (Access the authenticated user's API)
    read_repository (Allows read-only access to the repository)
    write_repository (Allows read-write access to the repository)

?

**Comment by tafkos** [comment]
![Screenshot_20210906_150711](https://user-images.githubusercontent.com/30288817/132215174-840e2696-3646-4bc8-a06a-769434bae219.jpg)

After clicking "Authorize" HTML ERROR 500 appears

**Comment by davidjgraph** [comment]
What domain is sending the 500, drawio.xyz.ru? Is there anything in the Tomcat logs about the error?

**Comment by tafkos** [comment]
ERROR 500 is from drawio.xxxxx.ru domain!

[Screenshot_20210906_151152](https://user-images.githubusercontent.com/30288817/132215794-4fc3c1f8-1bab-4d33-aeae-136a905ed5b1.jpg)
![Screenshot_20210906_151045](https://user-images.githubusercontent.com/30288817/132215801-bdcb8ab9-eb33-4535-9e96-1a664f2a8b6a.jpg)

**Comment by davidjgraph** [comment]
Set confidential to true. I don't see "trusted" as an option. Does it go away it you tick confidential?

**Comment by tafkos** [comment]
I removed those ticks to catch intermediate step when gitlab asks to authorizefor debugging purpose... If both ticks are yes then the behavior still the same except Gitlab doesn't ask to authorize application and proceeds to redirection link immediately.

**Comment by ashrafteleb** [comment]
Hi,

Please send us draw.io log. When 500 error is thrown, the log will contain an error similar to this:

```
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
java.io.IOException: Server returned HTTP response code: 400 for URL: http://10.0.0.206/oauth/token
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at com.mxgraph.online.AbsAuthServlet.contactOAuthServer(Unknown Source)
	at com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}

```

When we tried gitlab with latest draw.io docker image, it works fine
NOTE: Must use https

**Comment by tafkos** [comment]
<details>
    <summary>docker container log output</summary>
    <p>
<pre>
06-Sep-2021 20:27:25.565 SEVERE [http-nio-8080-exec-3] com.mxgraph.online.AbsAuthServlet.contactOAuthServer AUTH-SERVLET: [https://gitlab.xxxxxx.ru/oauth/token] ERROR: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderE
xception: unable to find valid certification path to requested target ->
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1151)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:448)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:425)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:241)
        at com.mxgraph.online.AbsAuthServlet.contactOAuthServer(Unknown Source)
        at com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1313)
        ... 41 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 47 more

06-Sep-2021 21:22:37.623 SEVERE [http-nio-8080-exec-4] com.mxgraph.online.AbsAuthServlet.contactOAuthServer AUTH-SERVLET: [https://gitlab.xxxxxx.ru/oauth/token] ERROR: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target ->
*******************************************
*******************************************
</pre>
   </p>
</details>

So... my Gitlab instance has default self-signed certificate which is rejected by Drawio... need to fix gitlab certificate issue first...

**Comment by ashrafteleb** [comment]
I'll close since it is a configuration issue

**Comment by tafkos** [comment]
This helped to finally fix the issue: https://stackoverflow.com/a/42377335/8655060

Just imported self-signed certificate of gitlab instance into java keystore inside self-hosted drawio container and restarted it!

Thanks everybody!
