### ISSUE TITLE
Click preview cannot be displayed

### ISSUE THREAD

**Issue by mysaber** [jgraph/drawio#2269]
![image](https://user-images.githubusercontent.com/3883686/134802134-f1057135-9b37-48a5-9f9b-b62dfd80b1a6.png)
com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5.js?externals=__local-default__:65 Refused to get unsafe header "ETag"
(anonymous) @ com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5.js?externals=__local-default__:65
r @ com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5.js?externals=__local-default__:65
d.onload @ com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5.js?externals=__local-default__:70
load (async)
request @ com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5.js?externals=__local-default__:70
b._handleRequest @ com.atlassian.plugins.atlassian-connect-plugin:ap-core-v5.js?externals=__local-default__:62
c._receiveMessage @ com.atlassian.plugins.atlassian-connect-plugin:ap-core-v5.js?externals=__local-default__:75
all.js:16 [Simple-XDM] mxSettings is not defined ReferenceError: mxSettings is not defined
    at EditorUi.init (https://ac.draw.io/js/viewer-static.min.js:3575:253)
    at EditorUi.init (https://ac.draw.io/js/viewer-static.min.js:3825:321)
    at new EditorUi (https://ac.draw.io/js/viewer-static.min.js:2152:142)
    at loadDiagramSuccess (https://ac.draw.io/connect/confluence/viewer.js:979:30)
    at r (https://connect-cdn.atl-paas.net/all.js:104:431)
    at b.c._handleResponse (https://connect-cdn.atl-paas.net/all.js:63:172)
    at b._receiveMessage (https://connect-cdn.atl-paas.net/all.js:21:77)

**Comment by davidjgraph** [comment]
Please provide some more details:

- Browser and version
- Any extension installed in your browser?
- Does this only happen in the viewer, nowhere else?

**Comment by davidjgraph** [comment]
This is fixed in 15.3.5.

If your browser caches an older version, go to https://ac.draw.io/clear.html and then try the viewer again.
