### ISSUE TITLE
Unable to authorize draw.io in self-hosted gitlab Nr2

### ISSUE THREAD

**Issue by maleksan** [jgraph/drawio#2649]
Hello, 
Similar issue was in this [Bug report](https://github.com/jgraph/drawio/issues/2507) and successfully fixed.
Now is the following situation:
With Docker version "16.5.3-alpine" all working fine and there is possibility authorize in self-hosted gitlab.
Installing the latest version "16.6.1" (none-Alpine version, as per this [change](https://github.com/jgraph/docker-drawio/commit/7cfd7692faf5d747635d0e2f72673103fa17f7ef)) with the same parameters and unfortunately in gui there is auth error "Unknown error".
Looking at Catalaina "localhost.2022-02-21.log" log file there is such error:
```
21-Feb-2022 11:37:32.260 INFO [http-nio-8080-exec-9] org.apache.catalina.core.ApplicationContext.log Marking servlet [GitlabAuthServlet] as unavailable
21-Feb-2022 11:37:32.261 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [GitlabAuthServlet]
        java.lang.ClassCastException: class com.mxgraph.online.GitlabAuthServlet cannot be cast to class jakarta.servlet.Servlet (com.mxgraph.online.GitlabAuthServlet is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @687ef2e0; jakarta.servlet.Servlet is in unnamed module of loader java.net.URLClassLoader @1e127982)
                at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1071)
                at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:128)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Unknown Source)
```
In the app log appears such error, which wasn't before in Alpine version:
```
21-Feb-2022 11:35:49.516 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
21-Feb-2022 11:35:49.541 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio-8443"]
21-Feb-2022 11:35:49.543 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[org.apache.coyote.http11.Http11NioProtocol-8443]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
at org.apache.catalina.connector.Connector.initInternal(Connector.java:1055)
at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
at org.apache.catalina.core.StandardService.initInternal(StandardService.java:556)
at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1042)
at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
at org.apache.catalina.startup.Catalina.load(Catalina.java:747)
at org.apache.catalina.startup.Catalina.load(Catalina.java:769)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:305)
at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
Caused by: java.lang.IllegalArgumentException: No SSLHostConfig element was found with the hostName [_default_] to match the defaultSSLHostConfigName for the connector [https-openssl-nio-8443]
at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:76)
at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:202)
at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1179)
at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1192)
at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:580)
at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:82)
at org.apache.catalina.connector.Connector.initInternal(Connector.java:1052)
... 13 more
21-Feb-2022 11:35:49.544 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [670] milliseconds
21-Feb-2022 11:35:49.600 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
21-Feb-2022 11:35:49.600 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.12]
```

**Comment by rickywu** [comment]
Have you enabled ssl both drawio and gitlab?

      DRAWIO_GITLAB_URL: http://xxx:8082/gitlab
      DRAWIO_GITLAB_ID: abc
      DRAWIO_GITLAB_SECRET: xyz

Should the redirect url to http://drawio.doman/gitlab?

**Comment by spacebug96** [comment]
I have the same draw.io&gitlab integration issue.  The mentioned problem occurs with latest (17.0.0) draw.io version also.
So, I have made rollback to old version 16.5.3 which is working fine.

**Comment by ashrafteleb** [comment]
Please try the latest docker image and let us know

**Comment by spacebug96** [comment]
@ashrafteleb I have tried version 17.1.3 & I can confirm the gitlab integration works as expected.
You can close this issue. Thank you

**Comment by maleksan** [comment]
> Please try the latest docker image and let us know

I confirm that 17.1.3 versions now works.
Thank you!

**Comment by kkeybbs** [comment]
The key is: ```class com.mxgraph.online.*Servlet cannot be cast to class jakarta.servlet.Servlet```

Tomcat 9.x (Servlet 4.0) 
Tomcat 10.x (Servlet 5.0)：`javax.*` =>  `jakarta.*`
jetty-server 11.0.7 has  `jakarta.*`.

So deploying draio in container with higher Servlet version will get the error.
How to solve:
- Upgrade drawio's servlet java files. (git clone the code, rename `javax.*` to  `jakarta.*`, and compile by yourself)
- Downgrade the container tomcat etc. 

**Downgrade to lower version** may be hard, and may have security problems some day), renaming import statments in files will be easier.

A pull-request doing this may demage others' work? So replace local (not verified):
```
sed -i -e 's/javax\.servlet\./jakarta\.servlet\./' src/main/java/com/mxgraph/online/*.java
```

ref
- https://stackoverflow.com/questions/64117697/servlet-class-org-restlet-ext-servlet-serverservlet-is-not-a-jakarta-servlet-ser
- https://stackoverflow.com/questions/65872072/jakarta-servlet-servletexception-class-com-practice-myservlet-is-not-a-servle
