### ISSUE TITLE
ExportProxyServlet removed in latest release (v18.0.8)

### ISSUE THREAD

**Issue by gek0** [jgraph/drawio#2830]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using the latest version v18.0.8 I can no longer export graphs to PDF for standalone self-hosted instance
Getting the following error
```
HTTP Status 404 – Not Found

Type Status Report
Message The requested resource [/service/0] is not available
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.63
```
I had to remove **DRAWIO_SELF_CONTAINED: "1"** from my environment but that uses a cloud export service on convert.diagrams.net which is not fully self-hosted anymore..
https://github.com/jgraph/docker-drawio/blob/v18.0.8/main/docker-entrypoint.sh#L25

**To Reproduce**
1. Go to File -> Export as
2. Click on "PDF..."
3. See error

**Expected behavior**
New window is opened as before and PDF generated from the source graph

- draw.io version -> 18.0.8

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox, Chromium
 - Version: latest

**Additional context**
I can see the applet removed https://github.com/jgraph/drawio/blob/dev/ChangeLog#L3 + https://github.com/jgraph/drawio/commit/7764b250b3fa58b249542f4ff9a1ddc1362cf88c
What is the new way to enable and use PDF export function?

**Comment by davidjgraph** [comment]
Have you customized ths build, or are you using fully as-is?

**Comment by gek0** [comment]
@davidjgraph as-is. Using tthe pre-built images from the docker repository

- jgraph/drawio:18.0.8
  - ENV:
    - DRAWIO_BASE_URL: "https://mydomain.com"
    - DRAWIO_VIEWER_URL: "https://mydomain.com/js/viewer.min.js"
    - DRAWIO_GOOGLE_APP_ID: "XXXXXX"
    - DRAWIO_GOOGLE_CLIENT_ID: XXXXXX.apps.googleusercontent.com
    - DRAWIO_GOOGLE_CLIENT_SECRET: XXXXXX
- jgraph/export-server:latest
  - ENV:
     - DRAWIO_SERVER_URL: "https://mydomain.com" 

When setting the DRAWIO_SELF_CONTAINED: "1" in the jgraph/drawio container I get the 404 error

EXPORT_URL seems to be removed as the option as well

**Comment by davidjgraph** [comment]
Fixed in 18.1.1, thanks for the report.

**Comment by gek0** [comment]
@davidjgraph  Tried the latest image. How long is the Export server timeout set?

This is what I get from the browser:

```
Request URL: https://mydrawio.example.com/service/0
Request Method: POST
Status Code: 504 Gateway Timeout
Remote Address: 10.xx.xx.xx:443
Referrer Policy: strict-origin-when-cross-origin
```

Export server container: 
Request is visible so it gets to the right place
```
info: Success xml=2332 embed=1 format=pdf dt=7593
::ffff:127.0.0.1 - - [23/May/2022:11:18:03 +0000] "POST /service/0 HTTP/1.1" 200 27876 "https://mydrawio.example.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
```

Drawio container logs:

```
23-May-2022 11:14:32.583 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [9392] milliseconds
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:783)
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:688)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:366)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
	at com.mxgraph.online.Utils.copy(Unknown Source)
	at com.mxgraph.online.Utils.copy(Unknown Source)
	at com.mxgraph.online.ExportProxyServlet.doRequest(Unknown Source)
	at com.mxgraph.online.ExportProxyServlet.doPost(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:135)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1384)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:773)
	at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:593)
	at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:537)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:547)
	at org.apache.coyote.http11.filters.IdentityOutputFilter.doWrite(IdentityOutputFilter.java:73)
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:194)
	at org.apache.coyote.Response.doWrite(Response.java:615)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:340)
	... 33 more
```

**Comment by gek0** [comment]
Also, what should be the value of EXPORT_URL if running in the same docker network as a standalone container? or inside k8s cluster?
I'm trying multiple configurations and non is valid

```
java.net.MalformedURLException: no protocol: "/service/0/"
java.net.MalformedURLException: no protocol: "http://image-export:8000/service/0"
java.net.MalformedURLException: no protocol: "image-export:8000/service/0"
java.net.MalformedURLException: no protocol: "http://localhost:8000/service/0"
```

And it's static inside the container as it is hardcoded in that process https://github.com/jgraph/docker-drawio/blob/dev/main/docker-entrypoint.sh#L27
