### ISSUE TITLE
Connection refused in drawio container after authorization from self-hosted gitlab docker container

### ISSUE THREAD

**Issue by kankan-k2** [jgraph/drawio#3079]
* [ Yes ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ Yes] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
after successful authorization on self hosted gitlab (docker container), redirect url to self hosted diagram.net app (docker container) throws HTTP error 500. The error message reads as:
This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500

**To Reproduce**
1. start up a docker container of gitlab with local port 9080 mapped to port 8080 of the docker container (http://localhost:9080)
2. Create an application named "localdiagrams" with below values:
Redirect URI: http://localhost:9090/gitlab
Confidential (checked)
Scopes selected: api, read_repository, write_repository
3. start up a docker container of diagram.net (aka drawio) with local port 9090 mapped to port 8080 of the docker container (http://localhost:9090) with the below variables set
DRAWIO_BASE_URL="http://localhost:8080"
DRAWIO_GITLAB_URL="http://localhost:9080"
DRAWIO_GITLAB_ID="<MyAppID>"
DRAWIO_GITLAB_SECRET="<MyAppSecret>"
4. Access, diagram.net app at localhost:9090 using http protocol only --> select Gitlab --> Create a blank diagram --> Authorize on Gitlab --> redirects to Gitlab url with the Authorize popup --> Click Authorize --> redirects to diagram.net app (self-hosted)

**Expected behavior**
The redirection should have worked and the diagram.net app's page should be displayed.
Redirected url is as below:
http://localhost:9090/gitlab?code=be1b7d500ae1434e0c899d2b4644279393fe0b40e099a01be85696292cd81a08&state=cId%3Df8f8cf12c37599fc88d1bc1f8b3e05d161a6a1e13f8a444c3e7d74ba12613b39%26domain%3Dlocalhost%26token%3Dd1m4nmsu881f58idm6t7jlemlqv02uk4ivb2b64st2fhrgrrdo5

**Screenshots**
![image](https://user-images.githubusercontent.com/33869369/193273076-a47e2c03-d60b-46c4-b021-a8a25feeebbd.png)
![image](https://user-images.githubusercontent.com/33869369/193273165-3711725b-ec2a-4ec4-8980-f2dcc5e1c24b.png)
![image](https://user-images.githubusercontent.com/33869369/193273256-0e6fbcf0-2a06-4893-bd67-5c583093858d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 20.3.7

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 11.6.7

**Additional context**
Error in the log message of drawio/diagram.net app (tomcat):

30-Sep-2022 10:08:39.800 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1316] milliseconds
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.mxgraph.online.AbsAuthServlet.contactOAuthServer(Unknown Source)
	at com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
30-Sep-2022 10:09:06.384 SEVERE [http-nio-8080-exec-6] com.mxgraph.online.AbsAuthServlet.contactOAuthServer AUTH-SERVLET: [http://localhost:9080/oauth/token] ERROR: Connection refused (Connection refused) ->

**Comment by rickywu** [comment]
try use https for gitlab

**Comment by ezesil** [comment]
Almost the same here, but i get java.net.UnknownHostException.

**Comment by m-mohamedin** [comment]
Hi,

We'll add support for http and localhost in the next version.

Please also note the DRAWIO_GITLAB_URL should be something like "http://localhost:9080/oauth/token" (for gitlab.com it is https://gitlab.com/oauth/token)

**Comment by davidjgraph** [comment]
Released in 21.3.3
