### ISSUE TITLE
Google Drive integration doesn't work

### ISSUE THREAD

**Issue by andyvgr** [jgraph/drawio#3320]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
So I've noticed a couple of bugs on the latest build.

    Google Drive integration doesn't work, I click google drive, It shows the account page, I click allow and when the Oauth2 points back to my site /google per the instructions nothing is there, I can go to the same site /google and indeed nothing is running there.

**To Reproduce Google Drive Issue**
1. Go to main screen
2. Click on google drive
3. Scroll down to select google account, it shows the usual app will have access to the following screen, then click allow
4. Blank 500 Error page, going to /google on the same docker instance shows the same error

**Expected behavior**
It should continue on from there and show the save options

**Screenshots**
Wouldn't help, just a blank page in firefox fox and an 500 server error in chrome based browsers

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [20.8.13]

**Desktop (please complete the following information):**
 - OS: [Win 11]
 - Browser [tested in chrome / firefox / brave / edge / multiple different pcs]
 - Version [newest of all above]

**Additional context**
Verified Docker is running, verified port is open

**Comment by andyvgr** [comment]
Just an update, I test with Ubuntu Server 22.04 and Rocky Linux 9 the same results, here is the error from the terminal when the failure happens:


root-drawio-1           |   "error": "invalid_grant",
root-drawio-1           |   "error_description": "Bad Request"
root-drawio-1           | }
root-drawio-1           | java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.googleapis.com/oauth2/v4/token
root-drawio-1           |       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
root-drawio-1           |       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
root-drawio-1           |       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
root-drawio-1           |       at com.mxgraph.online.AbsAuth.contactOAuthServer(Unknown Source)
root-drawio-1           |       at com.mxgraph.online.AbsAuth.doGetAbst(Unknown Source)
root-drawio-1           |       at com.mxgraph.online.GoogleAuthServlet.doGet(Unknown Source)
root-drawio-1           |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:670)
root-drawio-1           |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
root-drawio-1           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
root-drawio-1           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
root-drawio-1           |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
root-drawio-1           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
root-drawio-1           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
root-drawio-1           |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
root-drawio-1           |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
root-drawio-1           |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
root-drawio-1           |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
root-drawio-1           |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
root-drawio-1           |       at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
root-drawio-1           |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
root-drawio-1           |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
root-drawio-1           |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
root-drawio-1           |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
root-drawio-1           |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
root-drawio-1           |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
root-drawio-1           |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
root-drawio-1           |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
root-drawio-1           |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
root-drawio-1           |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
root-drawio-1           |       at java.base/java.lang.Thread.run(Unknown Source)
root-drawio-1           | 27-Jan-2023 18:29:21.470 SEVERE [http-nio-8080-exec-10] com.mxgraph.online.AbsAuth.contactOAuthServer AUTH-SERVLET: [https://www.googleapis.com/oauth2/v4/token] ERROR: Server returned HTTP response code: 400 for URL: https://www.googleapis.com/oauth2/v4/token -> {
root-drawio-1           |   "error": "invalid_grant",
root-drawio-1           |   "error_description": "Bad Request"
root-drawio-1           | }
root-drawio-1           |

**Comment by andyvgr** [comment]
Tested with a top domain and still /google doesn't load properly, any idea?
