### ISSUE TITLE
self-contained installation: service worker prefetches missing files

### ISSUE THREAD

**Issue by torkve** [jgraph/drawio#4681]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I have intranet self-contained installation of drawio with all internet activity disabled and `urlParams['offline']=1` enforced. 

Recently I got some reports from my colleagues with chromium-based browsers, that when they embed diagrams into their pages through iframe, they occasionally see no diagram until page reload. The only hint they have is the following message in the browser console:

```
PrecacheStrategy.js:142 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://drawio.domain/connect/jira/editor-1-3-3.html","status":404}]
    at C.O (https://drawio.domain/workbox-eb9c7348.js:1:10041)
    at async C._ (https://drawio.domain/workbox-eb9c7348.js:1:9639)
    at async C.U (https://drawio.domain/workbox-eb9c7348.js:1:8763)
O @ PrecacheStrategy.js:142
Object setTimeout (async)
(anonymous) @ timeout.js:17
cachePut @ timeout.js:17
O @ PrecacheStrategy.js:138
Object await in O (async)
_ @ PrecacheStrategy.js:71
Object await in _ (async)
U @ Strategy.js:144
Object await in U (async)
handleAll @ Strategy.js:135
(anonymous) @ PrecacheController.js:164
Object await in (anonymous) (async)
w @ waitUntil.js:18
install @ PrecacheController.js:151
```

When I started investigating, I found the following:

1. Service worker is effectively enabled always [when app is set to offline](https://github.com/jgraph/drawio/blob/a2685dd63e1475fd9aea14ef52ce3f1199f38b1e/src/main/webapp/js/diagramly/Editor.js#L200-L201) and PWA is not explicitly disabled.
2. [Service worker](https://github.com/jgraph/drawio/blob/a2685dd63e1475fd9aea14ef52ce3f1199f38b1e/src/main/webapp/service-worker.js) contains prefetch for file `connect/jira/editor-1-3-3.html`
3. This file is missing both in drawio git repository and in official docker image `jgraph/drawio`. I rebuilt docker image myself, and it seems it is not downloaded at any moment.
4. I do not know how `service-worker.js` is generated and if I can rebuild it during docker image build process.
5. Official installation at app.diagrams.net [has](https://app.diagrams.net/connect/jira/editor-1-3-3.html) this file, so it is not affected by the problem.

I still don't know yet if it is the root cause of the original problem my colleagues reported, but it seems at least a problem by itself.

**To Reproduce**
1. Install drawio on your own domain using official image `jgraph/drawio`
2. Open browser console in any chromium based browser (e.g. Google Chrome).
3. Go to `https://drawio.yourdomain/?offline=1`
4. See prefetch error in console.

**Expected behavior**
No prefetch error expected.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.8

**Desktop (please complete the following information):**
 - OS: Ubuntu, Mac OS X
 - Browser chrome
 - Browser Version: 108

**Smartphone (please complete the following information):**
Not tested

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**

**Comment by davidjgraph** [comment]
Is this still happening on latest?
